export const // Array of 32 locations (Global + Focus on Texas)
  shopLocations = [
    {
      name: 'America Headquaters:Houston, TX',
      lat: 29.7604,
      lng: -95.3698,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Austin, TX',
      lat: 30.2672,
      lng: -97.7431,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Dallas, TX',
      lat: 32.7767,
      lng: -96.797,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'San Antonio, TX',
      lat: 29.4241,
      lng: -98.4936,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'El Paso, TX',
      lat: 31.7619,
      lng: -106.485,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'New York, NY',
      lat: 40.7128,
      lng: -74.006,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Los Angeles, CA',
      lat: 34.0522,
      lng: -118.2437,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Chicago, IL',
      lat: 41.8781,
      lng: -87.6298,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Miami, FL',
      lat: 25.7617,
      lng: -80.1918,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Europe Headquaters:London, UK',
      lat: 51.5074,
      lng: -0.1278,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Paris, France',
      lat: 48.8566,
      lng: 2.3522,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Asia Headquaters:Tokyo, Japan',
      lat: 35.6895,
      lng: 139.6917,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Beijing, China',
      lat: 39.9042,
      lng: 116.4074,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Sydney, Australia',
      lat: -33.8688,
      lng: 151.2093,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Toronto, Canada',
      lat: 43.6532,
      lng: -79.3832,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Rio de Janeiro, Brazil',
      lat: -22.9068,
      lng: -43.1729,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Cape Town, South Africa',
      lat: -33.9249,
      lng: 18.4241,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Berlin, Germany',
      lat: 52.52,
      lng: 13.405,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Moscow, Russia',
      lat: 55.7558,
      lng: 37.6173,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Dubai, UAE',
      lat: 25.276987,
      lng: 55.296249,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Mexico City, Mexico',
      lat: 19.4326,
      lng: -99.1332,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Mumbai, India',
      lat: 19.076,
      lng: 72.8777,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Seoul, South Korea',
      lat: 37.5665,
      lng: 126.978,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Rome, Italy',
      lat: 41.9028,
      lng: 12.4964,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Bangkok, Thailand',
      lat: 13.7563,
      lng: 100.5018,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Istanbul, Turkey',
      lat: 41.0082,
      lng: 28.9784,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Athens, Greece',
      lat: 37.9838,
      lng: 23.7275,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Vienna, Austria',
      lat: 48.2082,
      lng: 16.3738,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Singapore',
      lat: 1.3521,
      lng: 103.8198,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Jakarta, Indonesia',
      lat: -6.2088,
      lng: 106.8456,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Lagos, Nigeria',
      lat: 6.5244,
      lng: 3.3792,
      iconUrl: 'assets/shop.svg',
    },
    {
      name: 'Africa Headquaters: Lilongwe, Malawi',
      lat: -13.9626,
      lng: 33.7741,
      iconUrl: 'assets/shop.svg',
    },
  ];
